### ISSUE TITLE
Opening existing blog causes a crash

### ISSUE THREAD

**Issue by jmcclelland** [SohanChy/Lipi#8]
All front matter should be in toml format... yet when I point lipi to an existing hugo site it immediately crashes with:

```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8413)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
	... 48 more
Caused by: java.lang.NullPointerException
	at view.wizard.WelcomeWizard.openDirBlog(WelcomeWizard.java:58)
	at view.wiza
```

**Comment by SohanChy** [comment]
I have final exams going on, 
I will try to look into this tommorow.
Please provide me a sample of your toml file if possible.

**Comment by jmcclelland** [comment]
Thanks!

```
languageCode = "en-us"
title = "Institute for the Study of Society"
baseurl = "https://instituteforthestudyofthescienceofsociety.org/"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
copyright = "Code released under the Apache 2.0 license."
noTimes = true

[author]
  name = "Institute for the Study of Society"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Welcome to the Institute for the Study of the Science of Society"
  Author = "Institute for the Study of Society"
  email = "joe@bob.org"
  postSummariesFrontPage = 4
  showReadTime = true

[[menu.main]]
  name = "home"
  url = "/"
```

**Comment by abioneperhobby** [comment]
Same error here.


> 
> 
> Microsoft Windows [Versione 10.0.17134.228]
> (c) 2018 Microsoft Corporation. Tutti i diritti sono riservati.
> 
> C:\Users\andrea.bisello>cd C:\Users\andrea.bisello\Desktop\Lipi.v0.6.0b_WIN
> 
> C:\Users\andrea.bisello\Desktop\Lipi.v0.6.0b_WIN>java -jar "Lipi 0.6.0b.jar"
> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
>         at view.wizard.WelcomeWizard.openDirBlog(WelcomeWizard.java:58)
>         at view.wizard.WelcomeWizard$1.handle(WelcomeWizard.java:119)
>         at view.wizard.WelcomeWizard$1.handle(WelcomeWizard.java:116)
>         at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
>         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
>         at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
>         at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
>         at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
>         at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
>         at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
>         at javafx.event.Event.fireEvent(Event.java:198)
>         at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
>         at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
>         at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
>         at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
>         at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
>         at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
>         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
>         at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
>         at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
>         at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
>         at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
>         at com.sun.glass.ui.View.notifyMouse(View.java:937)
>         at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
>         at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
>         at java.lang.Thread.run(Unknown Source)
> 
> C:\Users\andrea.bisello\Desktop\Lipi.v0.6.0b_WIN>


toml

> 
> baseURL = "http://localhost:1313/"
> languageCode = "it-IT"
> title = "Recensioni Facili"
> theme = "hugo-lamp"
> googleAnalytics = ""
> 
> [params]
>   subtitle = "Quello che ti basta sapere."
>   author = "Andrea Bisello"
>   logo = "/img/avatar.jpg"
>   description = "Non sai qualcosa? Te lo spieghiamo, in modo semplice."
>   paginate = 10
> 
>   # Publisher
>   ## adsensePublisher = "ca-pub-XXX"    # Required if you want to include Google Adsense
>   #adsenseSlot = "XXX"                   # Required slot to display ads
>   #adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads
> 
>   # SEO configs
>   seotitle = "Recensioni di elettrodomestici e tecnologia facili da capire"
>   #googleSiteVerification = ""    # Google Webmaster
>   #msValidate = "bing_site_verification_code"                  # Bing Webmaster
> 
>   # Social networks
>   #email = "name@domain.com"
>   #github = "huyb1991"
>   #twitter = "twitter_username"
>   #linkedin = "linkedin_username"
>   #facebook = "facebook_username"
>   #google = "googleplus_id_number"
>   #instagram = "instagram_username"
>   #youtube = "youtube_username"
>   #dribbble = "dribbble_username"
> 
> [taxonomies]
>   tag = "tags"
>   category = "categories"
> 
> [[menu.main]]
>   name = "Computer Portatili"
>   weight = 1
>   identifier = "notebook"
>   url = "/recensioni-computer-portatili-notebook/"
>
